import { roles } from "@/config/roles";
import { ro } from "date-fns/locale";
import type { LucideIcon } from "lucide-react";
import {
  ClipboardList,
  ClipboardPlus,
  LayoutDashboard,
  LogIn,
  LogOut as LogOutIcon,
  PackagePlus,
  PackageSearch,
  Settings,
  Users,
} from "lucide-react";

export type NavLink = {
  title: string;
  href: string;
  icon?: LucideIcon;
  roles?: string[];
  hotkey?: string;
  requiresAuth?: boolean;
  hideWhenAuthenticated?: boolean;
  action?: "logout";
};

export type NavSection = {
  title: string;
  items: NavLink[];
};

export const navSections: NavSection[] = [
  {
    title: "Workspace",
    items: [
      {
        title: "Home",
        href: "/",
        icon: LayoutDashboard,
      },
      {
        title: "Complaints",
        href: "/dashboard/complaints",
        icon: ClipboardList,
        roles: [
          roles.SUPPORT,
          roles.SUPER_ADMIN,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.ENGINEERING_MAINTENANCE,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.REGULATORY_AFFAIRS,
          roles.SALES_MARKETING,
          roles.STORE_INVENTORY,
          roles.AI_ML_TEAM,
          roles.SUPPORT,
          roles.SUPER_ADMIN,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.ENGINEERING_MAINTENANCE,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.REGULATORY_AFFAIRS,
          roles.SALES_MARKETING,
          roles.STORE_INVENTORY,
          roles.AI_ML_TEAM,
          roles.SOFTWARE
        ],
      },
      {
        title: "Device Requests",
        href: "/dashboard/device-material-issues",
        icon: PackageSearch,
        roles: [
          roles.SUPPORT,
          roles.SALES_MARKETING,
          roles.SUPER_ADMIN,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.ENGINEERING_MAINTENANCE,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.STORE_INVENTORY,
          roles.REGULATORY_AFFAIRS,
          roles.AI_ML_TEAM,
          roles.SUPPORT,
          roles.SALES_MARKETING,
          roles.SUPER_ADMIN,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.ENGINEERING_MAINTENANCE,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.STORE_INVENTORY,
          roles.REGULATORY_AFFAIRS,
          roles.AI_ML_TEAM,
          roles.SOFTWARE
        ],
      },
      {
        title: "CAPA Records",
        href: "/dashboard/capa",
        icon: ClipboardList,
        roles: [
          roles.SUPER_ADMIN,
          roles.SUPPORT,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.REGULATORY_AFFAIRS,
          roles.ENGINEERING_MAINTENANCE,
        ],
      },
    ],
  },
  {
    title: "Quick Actions",
    items: [
      {
        title: "New Complaint",
        href: "/dashboard/complaints/new",
        icon: ClipboardPlus,
        roles: [
          roles.SUPPORT,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.ENGINEERING_MAINTENANCE,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.REGULATORY_AFFAIRS,
          roles.SALES_MARKETING,
          roles.STORE_INVENTORY,
          roles.AI_ML_TEAM,
          roles.SUPER_ADMIN,
          roles.SUPPORT,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.ENGINEERING_MAINTENANCE,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.REGULATORY_AFFAIRS,
          roles.SALES_MARKETING,
          roles.STORE_INVENTORY,
          roles.AI_ML_TEAM,
          roles.SUPER_ADMIN,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.ENGINEERING_MAINTENANCE,
          roles.SUPPORT,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.REGULATORY_AFFAIRS,
          roles.SALES_MARKETING,
          roles.STORE_INVENTORY,
          roles.AI_ML_TEAM,
          roles.SUPER_ADMIN,
          roles.SUPPORT,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.ENGINEERING_MAINTENANCE,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.REGULATORY_AFFAIRS,
          roles.SALES_MARKETING,
          roles.STORE_INVENTORY,
          roles.AI_ML_TEAM,
          roles.SUPER_ADMIN,
        ],
        hotkey: "N",
      },
      {
        title: "New CAPA",
        href: "/dashboard/capa/new",
        icon: ClipboardPlus,
        roles: [
          roles.SUPER_ADMIN,
          roles.SUPPORT,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.REGULATORY_AFFAIRS,
          roles.ENGINEERING_MAINTENANCE,
          roles.SOFTWARE,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.STORE_INVENTORY,
          roles.SALES_MARKETING,
          roles.AI_ML_TEAM,
          roles.SUPER_ADMIN,
          roles.SUPPORT,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.REGULATORY_AFFAIRS,
          roles.ENGINEERING_MAINTENANCE,
          roles.SOFTWARE,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.STORE_INVENTORY,
          roles.SALES_MARKETING,
          roles.AI_ML_TEAM,
          roles.SUPER_ADMIN,
          roles.SUPPORT,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.REGULATORY_AFFAIRS,
          roles.ENGINEERING_MAINTENANCE,
          roles.SOFTWARE,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.STORE_INVENTORY,
          roles.SALES_MARKETING,
          roles.AI_ML_TEAM,
          roles.SUPER_ADMIN,
        ],
        hotkey: "C",
      },
      {
        title: "New Device Request",
        href: "/dashboard/device-material-issues/new",
        icon: PackagePlus,
        roles: [
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.AI_ML_TEAM,
          roles.ENGINEERING_MAINTENANCE,
          roles.STORE_INVENTORY,
          roles.REGULATORY_AFFAIRS,
          roles.SUPPORT,
          roles.SALES_MARKETING,
          roles.SUPER_ADMIN,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.REGULATORY_AFFAIRS,
          roles.SALES_MARKETING,
          roles.STORE_INVENTORY,
          roles.AI_ML_TEAM,
          roles.DESIGN_DEVELOPMENT,
          roles.DEVOPS,
          roles.CLINICAL_RESEARCH,
          roles.EMBEDDED_HARDWARE_FIRMWARE,
          roles.REGULATORY_AFFAIRS,
          roles.SUPPORT,
          roles.SALES_MARKETING,
          roles.SUPER_ADMIN,
          roles.QA,
          roles.QUALITY_ANALYST_SOFTWARE,
          roles.QA_HARDWARE,
          roles.PRODUCTION,
          roles.ENGINEERING_MAINTENANCE,
        ],
        hotkey: "D",
      },
    ],
  },
  {
    title: "Administration",
    items: [
      {
        title: "Admin Dashboard",
        href: "/admin/dashboard",
        icon: LayoutDashboard,
        roles: [roles.SUPER_ADMIN,roles.SUPPORT,roles.SOFTWARE,roles.DESIGN_DEVELOPMENT,roles.DEVOPS,roles.CLINICAL_RESEARCH,roles.AI_ML_TEAM,roles.QC_TEAM,roles.QUALITY_ANALYST_SOFTWARE,roles.QA_HARDWARE,roles.ENGINEERING_MAINTENANCE,roles.EMBEDDED_HARDWARE_FIRMWARE,roles.REGULATORY_AFFAIRS,roles.STORE_INVENTORY,roles.SALES_MARKETING,roles.PRODUCTION,roles.QA],
      },
      {
        title: "Site Settings",
        href: "/admin/settings",
        icon: Settings,
        roles: [roles.SUPER_ADMIN],
      },
      {
        title: "Manage Users",
        href: "/admin/users",
        icon: Users,
        roles: [roles.SUPER_ADMIN],
      },
    ],
  },
  {
    title: "Access",
    items: [
      {
        title: "Login",
        href: "/auth/login",
        icon: LogIn,
        hideWhenAuthenticated: true,
      },
      {
        title: "Logout",
        href: "#logout",
        icon: LogOutIcon,
        requiresAuth: true,
        action: "logout",
      },
    ],
  },
];

export const flatNavLinks: NavLink[] = navSections.flatMap((section) => section.items);
